# Generated by Django 3.1.7 on 2021-03-01 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('creat_date', models.DateTimeField(verbose_name='date created')),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_date', models.DateTimeField(verbose_name='date created')),
                ('text', models.CharField(max_length=200)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogwapp.proyect')),
            ],
        ),
    ]
