# Generated by Django 3.1.7 on 2021-03-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogwapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyect',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='proyect',
            new_name='project',
        ),
    ]
